<?php
define("user","用户名");
define("pass","密码");
define("sqlUser","数据库用户名");
define("sqlPass","数据库密码");
define("sqlAddress","数据库地址");
define("dbPort",3306);//端口
define("dbname","数据库名");
define("domainname","网站域名");
define("ErrorLog",false);//是否记录错误日志
define("WarnLog",false);//是否记录警告
?>
